#!/bin/bash
set -ueox pipefail

env

id

which docker

cat ~/.docker/config.json

cat <<EOF > ~/.docker/config.json
{
  "auths": {},
  "credHelpers": {
    "nscr.io": "nsc"
  }
}
EOF

cat ~/.docker/config.json

docker images

docker rmi nscr.io/01gr1g2rpb7ahzddy3f227exq9/test-cache:v1

ls -l /namespace/bin/

ls -l /dev/stdin
ls -l /proc/self/fd/0

docker-credential-nsc

echo "nscr.io" | docker-credential-nsc get

ls -l /var/run/nsc

ls -l $(which docker)

docker version

docker pull nscr.io/01gr1g2rpb7ahzddy3f227exq9/test-cache:v1

# docker compose -f .buildkite/docker/docker-compose.yml pull
