#!/bin/bash
set -ueox pipefail

env

id

which docker

cat <<EOF > ~/.docker/config.json
{
  "auths": {},
  "credHelpers": {
    "nscr.io": "nsc"
  }
}
EOF

cat ~/.docker/config.json

ls -l $(which docker)

docker version

echo nscr.io | docker-credential-nsc get

ls -l /var/run/nsc

cat ~/.docker/config.json

docker pull nscr.io/01gr1g2rpb7ahzddy3f227exq9/test-cache:v1

# docker compose -f .buildkite/docker/docker-compose.yml pull
