#!/bin/bash
set -ueo pipefail

env

COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker compose -f .buildkite/docker/docker-compose.yml -p buildkite018b4d9eb82c47a0a25e661e399e0a71 up -d --scale test=0 test